[tool.poetry]
name = "panorma"
version = "0.1.1"
description = ""
authors = ["Mayas Nova"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
