[tool.poetry]
name = "panorma"
version = "0.1.0"
description = ""
authors = ["MayasMess <test@test.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
